// =============================================================================
// Developer tools: element inspection, serialization, DevTools commands
// =============================================================================
using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Interop;
using System.Runtime.InteropServices;
using System.Text;
using System.Xml;
using System.Reflection;
using System.Windows.Documents;
using System.Windows.Media;
using System.Windows.Markup;
using Color = System.Windows.Media.Color;

public partial class AhkWpfEngine
{
    private bool _isInspectMode = false;
    private FrameworkElement _lastHighlightedElement = null;
    private bool IsIncludedInDevTools(DependencyObject root)
    {
        if (root == null) return false;
        var fe = root as FrameworkElement;

        // Skip internal control template parts unless explicitly generated by AHK
        if (fe != null && fe.TemplatedParent != null)
        {
            if (string.IsNullOrEmpty(fe.Uid) || !fe.Uid.StartsWith("ahk:"))
                return false;
        }

        string name = fe != null ? fe.Name : "";

        if (name.StartsWith("PART_")) return false;
        if (root is System.Windows.Controls.Primitives.ScrollBar) return false;
        if (root is System.Windows.Controls.ScrollContentPresenter) return false;

        return (!string.IsNullOrEmpty(name) && !name.StartsWith("PART_")) ||
               root is System.Windows.Controls.Button || root is System.Windows.Controls.TextBox ||
               root is System.Windows.Controls.ComboBox || root is System.Windows.Controls.TreeView ||
               root is System.Windows.Controls.ListBox || root is System.Windows.Controls.TabControl ||
               root is System.Windows.Controls.DataGrid || root is System.Windows.Controls.Image ||
               root is System.Windows.Controls.ScrollViewer || root is System.Windows.Controls.TextBlock ||
               root is System.Windows.Controls.Panel ||
               root is Window;
    }

    private bool IsPickerSkippable(FrameworkElement fe)
    {
        if (fe == null) return false;
        if (fe is Window) return true;
        string name = fe.Name ?? "";
        if (name == "AppGrid" || name == "AppScale" || name == "AppOverlay") return true;
        if (name.IndexOf("Overlay", StringComparison.OrdinalIgnoreCase) >= 0) return true;
        return false;
    }

    private FrameworkElement GetElementAtPoint(DependencyObject root, System.Windows.Point pos, Window win)
    {
        var uiRoot = root as UIElement;
        if (uiRoot != null && (!uiRoot.IsVisible || uiRoot.Opacity == 0)) return null;

        int count = System.Windows.Media.VisualTreeHelper.GetChildrenCount(root);
        for (int i = count - 1; i >= 0; i--)
        {
            var child = System.Windows.Media.VisualTreeHelper.GetChild(root, i);
            var result = GetElementAtPoint(child, pos, win);
            if (result != null) return result;
        }

        var fe = root as FrameworkElement;
        if (fe != null && fe.ActualWidth > 0 && fe.ActualHeight > 0)
        {
            if (IsIncludedInDevTools(fe) && !IsPickerSkippable(fe))
            {
                try
                {
                    var transform = fe.TransformToAncestor(win);
                    System.Windows.Rect bounds = new System.Windows.Rect(0, 0, fe.ActualWidth, fe.ActualHeight);
                    System.Windows.Rect rectOnWin = transform.TransformBounds(bounds);
                    if (rectOnWin.Contains(pos))
                    {
                        return fe;
                    }
                }
                catch { }
            }
        }
        return null;
    }

    private void Win_InspectMouseMove(object sender, System.Windows.Input.MouseEventArgs e)
    {
        if (!_isInspectMode) return;
        var win = sender as Window;
        if (win == null) return;

        var fe = GetElementAtPoint(win, e.GetPosition(win), win);
        if (fe != _lastHighlightedElement)
        {
            SetHighlight(fe, fe != null);
            _lastHighlightedElement = fe;
        }
    }

    private void Win_InspectMouseDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
    {
        if (!_isInspectMode) return;
        e.Handled = true;
        var win = sender as Window;
        if (win == null) return;

        var fe = GetElementAtPoint(win, e.GetPosition(win), win);
        if (fe != null)
        {
            string hash = fe.GetHashCode().ToString();
            SendToAhk("EVENT|" + winId + "|AppWindow|InspectPicked|" + BridgeUtil.LengthPrefix(hash) + "\n");
        }

        // Turn off inspect mode after picking
        _isInspectMode = false;
        SetHighlight(null, false);
        _lastHighlightedElement = null;
        win.PreviewMouseMove -= Win_InspectMouseMove;
        win.PreviewMouseDown -= Win_InspectMouseDown;
        win.Cursor = System.Windows.Input.Cursors.Arrow;
        SetHighlight(win, false);
    }


    // --- DevTools Helpers ---
    private XamlHighlightAdorner _currentAdorner;
    private void SetHighlight(FrameworkElement element, bool enable)
    {
        if (_currentAdorner != null)
        {
            var layer = AdornerLayer.GetAdornerLayer(_currentAdorner.AdornedElement);
            if (layer != null)
            {
                layer.Remove(_currentAdorner);
            }
            _currentAdorner = null;
        }

        if (enable && element != null)
        {
            var layer = AdornerLayer.GetAdornerLayer(element);
            if (layer != null)
            {
                _currentAdorner = new XamlHighlightAdorner(element);
                layer.Add(_currentAdorner);
            }
        }
    }

    private FrameworkElement FindElementByHash(DependencyObject root, string hash)
    {
        if (root == null || string.IsNullOrEmpty(hash)) return null;
        if (root.GetHashCode().ToString() == hash) return root as FrameworkElement;

        int children = VisualTreeHelper.GetChildrenCount(root);
        for (int i = 0; i < children; i++)
        {
            var found = FindElementByHash(VisualTreeHelper.GetChild(root, i), hash);
            if (found != null) return found;
        }
        return null;
    }

    private string SerializeVisualTree(DependencyObject root, int level = 0)
    {
        if (root == null) return "";
        var sb = new StringBuilder();
        var fe = root as FrameworkElement;

        string name = fe != null ? fe.Name : "";
        string type = root.GetType().Name;
        string visibility = fe != null ? fe.Visibility.ToString() : "Visible";
        double w = fe != null ? fe.ActualWidth : 0;
        double h = fe != null ? fe.ActualHeight : 0;
        string hash = root.GetHashCode().ToString();
        string uid = fe != null && fe.Uid != null && fe.Uid.StartsWith("ahk:") ? fe.Uid.Substring(4) : "";

        bool shouldInclude = IsIncludedInDevTools(root) || level == 0;

        if (shouldInclude)
        {
            sb.AppendFormat("{0}|{1}|{2}|{3:F0}|{4:F0}|{5}|{6}|{7}\n", level, type, name, w, h, visibility, hash, uid);
        }

        int children = VisualTreeHelper.GetChildrenCount(root);
        for (int i = 0; i < children; i++)
        {
            sb.Append(SerializeVisualTree(VisualTreeHelper.GetChild(root, i), level + 1));
        }
        return sb.ToString();
    }

    private static readonly System.Collections.Generic.Dictionary<System.Type, System.Reflection.PropertyInfo[]> _propertiesCache =
        new System.Collections.Generic.Dictionary<System.Type, System.Reflection.PropertyInfo[]>();

    private static readonly System.Collections.Generic.Dictionary<System.Type, System.Reflection.EventInfo[]> _eventsCache =
        new System.Collections.Generic.Dictionary<System.Type, System.Reflection.EventInfo[]>();

    private static readonly System.Collections.Generic.Dictionary<string, System.ComponentModel.DependencyPropertyDescriptor> _dpDescriptorCache =
        new System.Collections.Generic.Dictionary<string, System.ComponentModel.DependencyPropertyDescriptor>();

    private string InspectElementProperties(FrameworkElement element)
    {
        if (element == null) return "";
        var sb = new StringBuilder();

        System.Type type = element.GetType();
        System.Reflection.PropertyInfo[] properties;
        lock (_propertiesCache)
        {
            if (!_propertiesCache.TryGetValue(type, out properties))
            {
                properties = type.GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                _propertiesCache[type] = properties;
            }
        }

        foreach (var prop in properties)
        {
            try
            {
                if (!prop.CanRead) continue;
                if (prop.GetIndexParameters().Length > 0) continue;

                bool isLocal = false;
                bool isReadOnly = !prop.CanWrite || prop.GetSetMethod(false) == null;

                string key = type.FullName + "." + prop.Name;
                System.ComponentModel.DependencyPropertyDescriptor dpDescriptor;
                lock (_dpDescriptorCache)
                {
                    if (!_dpDescriptorCache.TryGetValue(key, out dpDescriptor))
                    {
                        dpDescriptor = System.ComponentModel.DependencyPropertyDescriptor.FromName(prop.Name, type, type);
                        _dpDescriptorCache[key] = dpDescriptor;
                    }
                }

                if (dpDescriptor != null)
                {
                    if (dpDescriptor.IsReadOnly) isReadOnly = true;
                    var vs = System.Windows.DependencyPropertyHelper.GetValueSource(element, dpDescriptor.DependencyProperty);
                    isLocal = (vs.BaseValueSource == System.Windows.BaseValueSource.Local);
                }

                object val = prop.GetValue(element, null);
                string strVal = "null";
                if (val != null)
                {
                    if (val is System.Collections.ICollection)
                    {
                        System.Collections.ICollection coll = (System.Collections.ICollection)val;
                        strVal = string.Format("Collection ({0} items)", coll.Count);
                    }
                    else
                    {
                        strVal = val.ToString();
                    }
                }

                string category = "Other";
                if (typeof(Delegate).IsAssignableFrom(prop.PropertyType) || prop.PropertyType.IsSubclassOf(typeof(Delegate)) || prop.Name.Contains("Event")) category = "Events";
                else if (prop.Name.Contains("Style") || prop.Name.Contains("Brush") || prop.Name.Contains("Color") || prop.Name.Contains("Margin") || prop.Name.Contains("Padding") || prop.Name.Contains("Thickness") || prop.Name.Contains("Background") || prop.Name.Contains("Foreground") || prop.Name.Contains("Font") || prop.Name.Contains("Border") || prop.Name.Contains("Align") || prop.Name.Contains("Width") || prop.Name.Contains("Height")) category = "Style";
                else category = "Properties";

                strVal = strVal.Replace("|", "&#x7C;").Replace("=", "&#x3D;").Replace("\n", "&#x0A;").Replace("\r", "&#x0D;");

                sb.AppendFormat("{0}|{1}|{2}|{3}:{4}={5}\n", category, isLocal ? "1" : "0", isReadOnly ? "1" : "0", prop.PropertyType.Name, prop.Name, strVal);
            }
            catch { }
        }

        System.Reflection.EventInfo[] events;
        lock (_eventsCache)
        {
            if (!_eventsCache.TryGetValue(type, out events))
            {
                events = type.GetEvents(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                _eventsCache[type] = events;
            }
        }

        foreach (var ev in events)
        {
            try
            {
                sb.AppendFormat("Events|0|1|{0}:{1}=CLR Event\n", ev.EventHandlerType.Name, ev.Name);
            }
            catch { }
        }
        return sb.ToString();
    }
}
